#! /bin/bash
alias editalias="vi ~/.alias"
alias editlocalrc="vi ~/.localrc"
alias resource="source ~/.bashrc"
alias resource_tmux="tmux source ~/.tmux.conf"

alias tm='tmux attach'
alias del='rm -rfi'
alias c="clear"
alias e="nvim -O"
alias vi="nvim -O"
alias :q="exit"

alias beep="echo -e \"\a\""
alias list-tcp-listeners="lsof -iTCP -sTCP:LISTEN -P +c0"

alias svim="sudo vi"
alias please="sudo !!"

alias wcl="wc -l"


# Directory navigation aliases
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias s='cd ..'

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias grv='grep -v'

# some more ls aliases
alias ll='ls -alF --human-readable'
alias la='ls -al --human-readable'
alias l='ls -alF --human-readable'

alias ports="netstat -tulanp"
alias psmem="ps auxf | sort -nr -k 4"
alias pscpu="ps auxf | sort -nr -k 3"

# build shortcuts


# git shortcuts
#
alias g="git"
alias gd="git diff"
alias gs="g status"
alias gcm="g commit -m"
alias ga="g add"
alias gcom="g checkout main"
alias gb="gco -b"
alias gl="git pull"
alias gco="git checkout"
